Modernize (thanks ChatGPT), remove jQuery, add README.
performous/web pull request #18
Opened 2023-05-09 13:47 UTC by Tronic

Avoid security warnings about jQuery.

2023-05-09 17:06 UTC, Tronic commented
The CI lacks SSH keys to Github so that it could clone (and presumably also push to after update) gh-pages. This happens in local-deploy.sh:

```
git clone --depth=50 --branch=gh-pages git@github.com:performous/web.git
```

2023-05-09 17:11 UTC, Tronic commented
The showcase image scroller should really be done with CSS animation, but ChatGPT didn't provide correct code for that change, so I left the JS implementation (but at least it uses requestAnimationFrame to run smoother).

2023-05-09 17:22 UTC, Tronic commented
Also this way of updating keeps old files that previously existed in gh-pages (such as the deleted jQuery files that GitHub keeps sending me warnings of). I suggest you put all static files in htdocs-binary, remove that git clone from the script such that no old files are placed in the generated web folder, and change your CI so that it deleted all old files and then adds the files from the web folder (I think git will still track changes as modifications if the same file was deleted and added in the same commit).

2023-05-24 10:51 UTC, Tronic commented
Still getting those jQuery security alerts. Could you get this deployed please?

2023-06-06 13:38 UTC, Tronic commented
@Baklap4 Hello?

2023-07-22 18:10 UTC, ooshlablu commented
@Tronic I tried to see what the issue with Semaphore was, but it never loads the log or anything when I look at it. I do have a task to convert this over to GitHub Actions at some point. I did start a new job a few weeks ago, so I'm pretty busy at the moment, but I'm hoping I will get to it soon. If this PR isn't merged by that point then I'll ping you again, and we can rebase and get it moving.

2023-08-06 16:55 UTC, Baklap4 commented
@Tronic i've rebased this on to current master. This will make sure GH-Actions run and i can try it out locally. If all is well it'll get merged right away. Thanks for updating sources!

2023-08-06 16:59 UTC, Baklap4 requested changes

2023-08-06 16:59 UTC, Baklap4 commented on htdocs-source/Model.htm
> +    <source src="/bgs/GoldenDust.webm" type="video/webm">
These do not need the first `/` as this will make it look for the root. It's better to make them relative, will fix that in a few

2023-08-06 17:04 UTC, Baklap4 requested changes

2023-08-06 17:04 UTC, Baklap4 commented on htdocs-binary/js/main.js
> +})
Getting an error here:
```
Uncaught (in promise) DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'file:///C:/Users/ArjanSpieardGuideID/OneDrive%20-%20GuideID/Downloads/web-output%20(1)/about' cannot be created in a document with origin 'null' and URL 'file:///C:/Users/ArjanSpieardGuideID/OneDrive%20-%20GuideID/Downloads/web-output%20(1)/index.html'.
    at HTMLDocument.<anonymous> (file:///C:/Users/ArjanSpieardGuideID/OneDrive%20-%20GuideID/Downloads/web-output%20(1)/js/main.js:37:11)
```

2023-08-06 18:03 UTC, Baklap4 commented on htdocs-binary/js/main.js
> +})
Running a local server instead of via file it seems to work.. Let's merge this

2023-08-06 18:09 UTC, Baklap4 approved these changes
Thanks for the update @Tronic 

Nothing needs to be done anymore since we auto-deploy the website now. Thanks :)

2023-08-06 18:09 UTC, merged